In [1]:
import numpy as np

In [2]:
# Phát sinh mảng 2 chiều có kích thước 5 x 3 với các phần tử có giá trị phát sinh ngẫu nhiên từ 1 đến 10 với np.random.seed(2)
np.random.seed(2)
arr1 = np.random.randint(1,11,size=(5, 3))
arr1

array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6],
       [5, 5, 6],
       [8, 4, 7]])

In [3]:
val,count = np.unique(arr1,return_counts=True)
val

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
count

array([1, 2, 1, 2, 2, 2, 2, 3], dtype=int64)

In [5]:
# thay thế phần tử <5 với phần tử xuất hiện nhiều nhất trong mảng
arr1[arr1 < 5] = val[count == max(count)][0]
arr1

array([[9, 9, 7],
       [9, 9, 8],
       [9, 9, 6],
       [5, 5, 6],
       [8, 9, 7]])

In [6]:
# In ra các phần tử < 8 trong mảng 
arr1[arr1 < 8]

array([7, 6, 5, 5, 6, 7])