# Câu 1. Numpy Array

In [ ]:
import numpy as np

### 1. Tạo mảng arr1 ngẫu nhiên 10 phần tử số nguyên từ 10-20 với np.random.seed(3)

In [36]:
np.random.seed(3)
arr1 = np.random.randint(10, 21, 10)
arr1

array([20, 18, 19, 13, 18, 18, 10, 15, 13, 20])

### 2. Phát sinh mảng arr2 ngẫu nhiên 10 phần tử số nguyên từ 11-30 với np.random.seed(3)

In [37]:
np.random.seed(3)
arr2 = np.random.randint(11, 31, 10)
arr2

array([21, 14, 19, 11, 30, 21, 22, 20, 21, 17])

### 3. In ra các phần tử xuất hiện trong cả 2 mảng arr1, arr2

In [38]:
np.intersect1d(arr1, arr2)

array([19, 20])

### 4. Sắp xếp lại mảng arr1 theo thứ tự tăng dần

In [39]:
np.sort(arr1)

array([10, 13, 13, 15, 18, 18, 18, 19, 20, 20])

### 5. In ra các phần tử trong mảng arr2 là số nguyên tố

In [40]:
def is_prime(n):
  for i in range(2,n):
    if (n % i) == 0:
      return False
  return True

cond = [is_prime(x) for x in arr2]
arr2[cond]

array([19, 11, 17])