# Bai Tap 1

## 1.a
1. Tạo numpy array arr có giá trị từ 0-9. Hiển thị các phần tử có trong arr, xem kiểu dữ liệu và kích thước của arr.
2. Từ array arr ở câu 1 => tạo arr_odd và arr_even.
3. Từ array arr ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100.

In [1]:
import numpy as np
arr = np.arange(10)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
int32


In [2]:
arr_odd = arr[arr%2!=0]
arr_even = arr[arr%2==0]
print(arr_odd)
print(arr_even)

[1 3 5 7 9]
[0 2 4 6 8]


In [3]:
arr_update_1 = arr.copy()
arr_update_1[arr_update_1 % 2 != 0] = 100
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]


## 1.b
1. Cho 2 array arr_a = [1,2,3,2,3,4,3,4,5,6] và arr_b = [7,2,10,2,7,4,9,4,9,8], tạo array arr_c chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a và arr_b.
2. Từ arr_a và arr_b ở câu 1 => Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a.
3. Cho arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]), hãy tạo arr_f chỉ chứa các phần tử có giá trị từ 5 đến 10 của arr_e.

In [6]:
arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])
arr_c = np.intersect1d(arr_a, arr_b)
print(arr_c)
arr_d = np.setdiff1d(arr_a, arr_b)
print(arr_d)

[2 4]
[1 3 5 6]


In [7]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print(arr_f)

[ 6  9 10  8  6]


## 1.c
1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.
2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.
3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác 0.
4. Từ arr_k của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.
5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.
6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

In [9]:
arr_zeros = np.zeros(10)
arr_zeros[4] = 1
print(arr_zeros)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
arr_h = np.linspace(10, 24, 15, dtype="int")
print(arr_h[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
print(arr_l)

[1 2 8 2 1 3 5]


In [15]:
arr_k = np.append(arr_k, [10,20])
print(arr_k)

[ 1  2  0  8  2  0  1  3  0  5  0 10 20]


In [16]:
arr_k = np.insert(arr_k, 5 , 100)
print(arr_k)

[  1   2   0   8   2 100   0   1   3   0   5   0  10  20]


In [17]:
arr_k = np.delete(arr_k, [0, 1, 2])
print(arr_k)

[  8   2 100   0   1   3   0   5   0  10  20]


# Bai Tap 2
Dữ liệu heights (tính theo inches) và weights (tính theo pounds) là chiều cao và cân nặng của các cầu thủ có tham gia 1 số giải của MLB. Cho tập tin dữ liệu heights_1.txt, weights_1.txt => hãy chép dữ liệu từ tập tin này vào list là height, weight, và thực hiện các yêu cầu sau:

## 2.1 - 2.2
Tạo numpy array arr_height từ list height.</br>
Tạo numpy array arr_weight từ list weight.

In [21]:
def get_data(fname):
    f = open(fname)
    data = f.read()
    f.close()
    return np.array(eval(data))
arr_height = get_data('heights_1.txt')
arr_weight = get_data('weights_1.txt')
print(height)
print(weight)

[74 74 72 ... 75 75 73]
[180 215 210 ... 205 190 195]


## 2.3
Cho hệ số quy đổi từ inch sang m là 0.0254, tạo arr_height_m dựa trên công thức: arr_height * hệ số quy đổi.

In [22]:
arr_height_m = arr_height * 0.0254
print(arr_height_m)

[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


## 2.4
Cho hệ số quy đổi từ pound sang kg là 0.453592, tạo arr_weight_kg dựa trên công thức: arr_weight * hệ số quy đổi.

In [23]:
arr_weight_kg = arr_weight *  0.453592
print(arr_weight_kg)

[81.64656 97.52228 95.25432 ... 92.98636 86.18248 88.45044]


## 2.5
Tính BMI của arr_height_m và arr_weight_kg theo công thức BMI = Cân nặng / (Chiều cao * Chiều cao), và lưu vào arr_bmi.

In [25]:
arr_bmi = arr_weight_kg / (arr_height_m * arr_height_m)
print(arr_bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


## 2.6
Cho biết giá trị cân nặng ở vị trí index = 50 trong arr_weight_kg

In [26]:
print(arr_weight_kg[50])

90.7184


## 2.7
Tạo arr_height_m_100 gồm các phần tử có vị trí index từ 100 đến 110 (lấy cả index 110) trong arr_height_m

In [33]:
arr_height_m_100 = arr_height_m[100:110+1]
print(arr_height_m_100)

[1.8542 1.8796 1.8288 1.8542 1.7526 1.8288 1.8542 1.905  1.905  1.8542
 1.8288]


## 2.8
Cho biết các cầu thủ bóng chày có bmi < 21 trong arr_bmi

In [28]:
print(arr_bmi[arr_bmi < 21])

[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


## 2.9 2.10 2.11
Cho biết chiều cao trung bình và cân nặng trung bình của các cầu thủ
Cho biết chiều cao và cân nặng lớn nhất của các cầu thủ
Cho biết chiều cao và cân nặng nhỏ nhất của các cầu thủ

In [31]:
print("Chieu cao trung binh:", np.mean(arr_height_m))
print("Can nang trung binh:", np.mean(arr_weight_kg))
print("Chieu cao lon nhat:", np.max(arr_height_m))
print("Can nang lon nhat:", np.max(arr_weight_kg))
print("Chieu cao nho nhat:", np.min(arr_height_m))
print("Can nang nho nhat:", np.min(arr_weight_kg))

Chieu cao trung binh: 1.8717172413793102
Can nang trung binh: 91.33019058916256
Chieu cao lon nhat: 2.1082
Can nang lon nhat: 131.54167999999999
Chieu cao nho nhat: 1.7018
Can nang nho nhat: 68.0388


## 2.12
cho biết các vận động viên có chiều cao lớn nhất tại các vị trí index

In [46]:
max = np.max(arr_height_m)
indexs = np.where(arr_height_m == max)
print(indexs[0][0])
print(max)

909
2.1082


## 2.13
In ra chiều cao tăng dần, giảm dần

In [44]:
print(np.sort(arr_height_m))
print(np.sort(arr_height_m)[::-1])

[1.7018 1.7018 1.7272 ... 2.0828 2.0828 2.1082]
[2.1082 2.0828 2.0828 ... 1.7272 1.7018 1.7018]
