# NumPy

## Khai bao

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print("a:", a, "Type of a:", type(a), "Item type:", a.dtype)

b = np.array([1, 2.3, 5])
print("b:", b, "Type of b:", type(b), "Item type:", b.dtype)

c = np.array([1, 2.3, "hi"])
print("c:", c, "Type of c:", type(c), "Item type:", c.dtype)

d = np.array([1,2,0], dtype=bool)
print("d:", d, "Type of d:", type(d), "Item type:", d.dtype)

e = np.array([1,2,0], dtype="i2")
print("e:", e, "Type of e:", type(e), "Item type:", e.dtype)

print("Size:", e.size, "Shape:", e.shape, "ndim:", e.ndim, "item size:", e.itemsize)

a: [1 2 3] Type of a: <class 'numpy.ndarray'> Item type: int64
b: [1.  2.3 5. ] Type of b: <class 'numpy.ndarray'> Item type: float64
c: ['1' '2.3' 'hi'] Type of c: <class 'numpy.ndarray'> Item type: <U32
d: [ True  True False] Type of d: <class 'numpy.ndarray'> Item type: bool
e: [1 2 0] Type of e: <class 'numpy.ndarray'> Item type: int16
Size: 3 Shape: (3,) ndim: 1 item size: 2


In [5]:
f = np.arange(1, 11)
print(f)

[ 1  2  3  4  5  6  7  8  9 10]


## Truy xuat numby array theo index

In [ ]:
#  0  1  2  3  4  5
# -6 -5 -4 -3 -2 -1
print(f[-1:-6:-1]) # start:end:reverse
print(f[-1:-4:-1])
print(f[::-1]) # Invert

indexs = [0, 1, 5]
print(f[indexs])

## Truy xuat theo dieu kien

In [7]:
cond = f > 5
print(cond, "Type of cond:", type(cond))
print(f[cond])

print(f[f % 2 == 0])
print(f[~(f % 2 == 0)])
print(f[(f > 5) & (f < 9)])

[False False False False False  True  True  True  True  True] Type of cond: <class 'numpy.ndarray'>
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[1 3 5 7 9]
[6 7 8]


## Cap nhat

In [6]:
f[:-6:-1] = 100
print(f)
f[f>=100] = f[f>=100] + 1
print(f)

[  1   2   3   4   5 100 100 100 100 100]
[  1   2   3   4   5 101 101 101 101 101]


## Them

In [8]:
f1 = np.append(f, [10, 20])
print(f1)
f2 = np.insert(f, 0, [11, 22])
print(f2)
f3 = np.insert(f, [1,3], [11])
print(f3)

[  1   2   3   4   5 101 101 101 101 101  10  20]
[ 11  22   1   2   3   4   5 101 101 101 101 101]
[  1  11   2   3  11   4   5 101 101 101 101 101]


## Xoa

In [9]:
f4 = np.delete(f, 1)
print(f4)

[  1   3   4   5 101 101 101 101 101]


## Thong ke

In [13]:
print("Sum:", np.sum(f))
print("Min:", np.min(f))
print("Max:", np.max(f))
print("Mean:", np.mean(f))
print("Median:", np.median(f))
print("std:", np.std(f))

Sum: 520
Min: 1
Max: 101
Mean: 52.0
Median: 53.0
std: 49.01020301937138


## Sort

In [15]:
print("Sort asc:", np.sort(f))
print("Sort des:", np.sort(f)[::-1])

Sort asc: [  1   2   3   4   5 101 101 101 101 101]
Sort des: [101 101 101 101 101   5   4   3   2   1]


## Operator

In [39]:
print("Operator plus 1:", f + 1)
print("Phep giao:", np.intersect1d([10, 20, 40], [10, 40]))
print("Phan tu hieu:", np.setdiff1d([10, 20, 40], [10, 40]))

Operator plus 1: [  2   3   4   5   6 102 102 102 102 102]
Phep giao: [10 40]
Phan tu hieu: [20]


## Ep kieu

In [17]:
f5 = f.astype(float)
print("Ep kieu astype:", f5)

[  1.   2.   3.   4.   5. 101. 101. 101. 101. 101.]


## Utils

In [36]:
print("Array builder zeros:", np.zeros(10))
print("Array builder ones:", np.ones(10))
print("Array builder custom:", np.full(shape=(10,),fill_value=10))

print("Linspace 1:", np.linspace(2, 10, 5, endpoint=False)) # Tu 2 den 10, lấy 5 phần tử CÁCH ĐỀU NHAU, ko bao gồm end
print("Linspace 2:", np.linspace(2, 10, 5, endpoint=True)) # Tu 2 den 10, lấy 5 phần tử CÁCH ĐỀU NHAU

np.random.seed(1) # Mark stored this random
print("Random int:", np.random.randint(1, 6, 2))

f6 = np.loadtxt("data.txt", delimiter=",")
print("Data file:", f6)

Array builder zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array builder ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array builder custom: [10 10 10 10 10 10 10 10 10 10]
Linspace 1: [2.  3.6 5.2 6.8 8.4]
Linspace 2: [ 2.  4.  6.  8. 10.]
Random int: [4 5]
Data file: [1.57 1.65 1.63 1.58 1.57 1.68 1.65 1.7  1.64 1.67]
