# Mảng một chiều NumPy

In [2]:
import numpy as np

## 1. Khởi tạo
`dtype`: Kiểu dữ liệu của các phần tử trong mảng numpy <br>
`size`: Số phần tử <br>
`ndim`: Số chiều của mảng <br>
`shape`: Kiểu tuple biểu thị số chiều, số phần tử trong mỗi chiều <br>
`itemsize`: Kích thức bộ nhớ item

### 1.1. Khởi tạo từ list

In [10]:
# Mảng số nguyên
a = np.array([1,2,3])
print("a:", a, "\nitem type:", a.dtype, "- ndim:", a.ndim, "- shape:", a.shape, "- item size:", a.itemsize)

a: [1 2 3] 
item type: int64 - ndim: 1 - shape: (3,) - item size: 8


In [11]:
# Mảng lẫn lộn
a = np.array([1, 2.3, "hi"])
print("a:", a, "\nitem type:", a.dtype, "- ndim:", a.ndim, "- shape:", a.shape, "- item size:", a.itemsize)

a: ['1' '2.3' 'hi'] 
item type: <U32 - ndim: 1 - shape: (3,) - item size: 128


In [12]:
# Mảng số nguyên 1 byte
a = np.array([1,2,0], dtype="i1")
print("a:", a, "\nitem type:", a.dtype, "- ndim:", a.ndim, "- shape:", a.shape, "- item size:", a.itemsize)

a: [1 2 0] 
item type: int8 - ndim: 1 - shape: (3,) - item size: 1


In [49]:
# Kích thước bộ nhớ mảng
a.itemsize * a.size

80

### 1.2. Khởi tạo từ file

In [46]:
# Load từ file
np.loadtxt("data/data.txt", delimiter=",")

array([1.57, 1.65, 1.63, 1.58, 1.57, 1.68, 1.65, 1.7 , 1.64, 1.67])

### 1.3. Các hàm builder

In [48]:
# Khởi tạo từ range
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# Array builder zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# Array builder ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
# Array builder custom
np.full(shape=(10,), fill_value=10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [43]:
# Linspace, fill 5 item cách đều nhau từ 2 đến 10
np.linspace(2, 10, 5, endpoint=True)

array([ 2.,  4.,  6.,  8., 10.])

## 2. Truy xuất phần tử

### 2.1. Truy xuất theo index
`[start:stop:step]`

In [14]:
# 5 items cuối theo thứ tự ngược
a[-1:-6:-1]

array([10,  9,  8,  7,  6])

In [15]:
# Đảo ngược mảng
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
# Theo mảng indexes
indexes = [0, 1, 5]
a[indexes]

array([1, 2, 6])

### 2.2. Truy xuất theo điều kiện

In [18]:
# Các phần tử lớn hơn 5
cond = a > 5
a[cond]

array([ 6,  7,  8,  9, 10])

In [19]:
# Các phần tử chẵn
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [20]:
# Các phần tử lớn hơn 5 và nhỏ hơn 9
a[(a > 5) & (a < 9)]

array([6, 7, 8])

## 3. Thao tác với NumPy array

### 3.1. Thêm vào array

In [22]:
# Dùng append thêm vào cuối
np.append(a, [11, 12])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
# Dùng insert thêm vào đầu
np.insert(a, 0, [-1, 0])

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Dùng insert thêm vào indexes
np.insert(a, [1,3], [100])

array([  1, 100,   2,   3, 100,   4,   5,   6,   7,   8,   9,  10])

### 3.2. Sửa giá trị trong array

In [26]:
# Sửa 5 phần tử cuối thành 100
a[:-6:-1] = 100
a

array([  1,   2,   3,   4,   5, 100, 100, 100, 100, 100])

In [27]:
# Sửa phần tử >= 100 tăng lên 1
a[a>=100] = a[a>=100] + 1
a

array([  1,   2,   3,   4,   5, 101, 101, 101, 101, 101])

### 3.3. Xóa phần tử trong array

In [28]:
# Xóa phần tử tại index 1
np.delete(a, 1)

array([  1,   3,   4,   5, 101, 101, 101, 101, 101])

## 4. Thống kê

In [50]:
print("Sum:", np.sum(a))
print("Min:", np.min(a))
print("Max:", np.max(a))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Std:", np.std(a))

Sum: 520
Min: 1
Max: 101
Mean: 52.0
Median: 53.0
Std: 49.01020301937138


## 5. Sort

In [30]:
# Sort tăng dần
np.sort(a)

array([  1,   2,   3,   4,   5, 101, 101, 101, 101, 101])

In [31]:
# Sort giảm dần
np.sort(a)[::-1]

array([101, 101, 101, 101, 101,   5,   4,   3,   2,   1])

## 6. Operator

In [32]:
# Cộng
a + 1

array([  2,   3,   4,   5,   6, 102, 102, 102, 102, 102])

In [33]:
# Phép giao
np.intersect1d([10, 20, 40], [10, 40])

array([10, 40])

In [34]:
# Phép hiệu 
np.setdiff1d([10, 20, 40], [10, 40])

array([20])

## 7. Utils

In [35]:
# Ép kiểu cả mảng
a.astype(float)

array([  1.,   2.,   3.,   4.,   5., 101., 101., 101., 101., 101.])

In [51]:
# Random low, high, size
np.random.seed(1)
np.random.randint(1, 6, 4)

array([4, 5, 1, 2])