# Mảng nhiều chiều NumPy

In [30]:
import numpy as np

## 1. Khởi tạo

### 1.1. Khởi tạo từ list

In [34]:
a = np.array([[38, 13, 73],
       [10, 76,  6],
       [80, 65, 17],
       [ 2, 77, 72],
       [ 7, 26, 51]])
print("a:", a, "\nitem type:", a.dtype, "- ndim:", a.ndim, "- shape:", a.shape, "- item size:", a.itemsize)

a: [[38 13 73]
 [10 76  6]
 [80 65 17]
 [ 2 77 72]
 [ 7 26 51]] 
item type: int64 - ndim: 2 - shape: (5, 3) - item size: 8


### 1.2. Các hàm builder

In [25]:
# Matrix builder zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Matrix builder ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# Matrix builder custom
np.full(shape=(3,3), fill_value=10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## 2. Truy xuất phần tử

### 2.1. Truy xuất theo dòng, cột

In [3]:
# Dòng 1, cột 1
a[1][1]
a[1,1]

76

In [4]:
# Dòng cuối, cột cuối
a[-1,-1]

51

### 2.2. Truy xuất nhiều phần tử
`[start:stop, start:stop]`</br>
`[[indexes], [indexes]]`

In [6]:
# Dòng 1
a[1,:]
a[1]

array([10, 76,  6])

In [7]:
# Cột 2
a[:,2]

array([73,  6, 17, 72, 51])

In [8]:
# Dòng 1->3
a[1:4,:]

array([[10, 76,  6],
       [80, 65, 17],
       [ 2, 77, 72]])

In [35]:
# 2 cột đầu
a[:,:2]

array([[38, 13],
       [10, 76],
       [80, 65],
       [ 2, 77],
       [ 7, 26]])

In [37]:
# 2 cột cuối
a[:,-2:]

array([[13, 73],
       [76,  6],
       [65, 17],
       [77, 72],
       [26, 51]])

In [9]:
# Lấy phần tử 65, 17, 77, 72
a[2:4,1:]

array([[65, 17],
       [77, 72]])

In [10]:
# Lấy phần tử 10, 6, 2, 72
a[1::2,::2]

array([[10,  6],
       [ 2, 72]])

### 2.3. Truy xuất theo điều kiện

In [11]:
# Phần tử chia hết cho 2
a[a % 2 == 0]

array([38, 10, 76,  6, 80,  2, 72, 26])

In [12]:
# Phần tử chia hết cho 2 và lớn hơn 70
a[(a % 2 == 0) & (a > 70)]

array([76, 80, 72])

### 2.4. Truy xuất mảng 3 chiều
`tenmang[index ma tran, index dong, index cot]`

In [13]:
np.random.seed(1)
b = np.random.randint(1, 101, size=(2,5,3))
b

array([[[38, 13, 73],
        [10, 76,  6],
        [80, 65, 17],
        [ 2, 77, 72],
        [ 7, 26, 51]],

       [[21, 19, 85],
        [12, 29, 30],
        [15, 51, 69],
        [88, 88, 95],
        [97, 87, 14]]])

In [14]:
# Ma trận 0, dòng 1, cột 1
b[0,1,1]

76

In [15]:
# Ma trận 1 trở đi
b[1:]

array([[[21, 19, 85],
        [12, 29, 30],
        [15, 51, 69],
        [88, 88, 95],
        [97, 87, 14]]])

In [16]:
# Chỉ mỗi ma trận 1
b[1]

array([[21, 19, 85],
       [12, 29, 30],
       [15, 51, 69],
       [88, 88, 95],
       [97, 87, 14]])

In [17]:
# Lay phần tử 76, 6, 65, 17, 29, 30, 51, 69
b[:,1:3,1:3]

array([[[76,  6],
        [65, 17]],

       [[29, 30],
        [51, 69]]])

## 3. Thao tác

### 3.1. Thêm dòng, cột vào ma trận
**`np.insert`** or **`np.concatenate`**

In [18]:
# Dùng insert, thêm [1, 2, 3] vào dòng 5
np.insert(a, 5, [1, 2, 3], axis=0)

array([[38, 13, 73],
       [10, 76,  6],
       [80, 65, 17],
       [ 2, 77, 72],
       [ 7, 26, 51],
       [ 1,  2,  3]])

In [19]:
# Dùng concatenate, thêm [[0, 0, 0, 0, 0]] vào cột cuối
new_arr = np.array([[0, 0, 0, 0, 0]])
np.concatenate([a, new_arr.T], axis=1)

array([[38, 13, 73,  0],
       [10, 76,  6,  0],
       [80, 65, 17,  0],
       [ 2, 77, 72,  0],
       [ 7, 26, 51,  0]])

### 3.2. Sửa giá trị trong ma trận

In [21]:
# Sửa dòng 0, cột 0 thành 100
a[0,0] = 100
a

array([[100,  13,  73],
       [ 10,  76,   6],
       [ 80,  65,  17],
       [  2,  77,  72],
       [  7,  26,  51]])

### 3.3. Xóa phần tử trong ma trận

In [22]:
# Xóa cột cuối
np.delete(a, -1, axis=1)

array([[100,  13],
       [ 10,  76],
       [ 80,  65],
       [  2,  77],
       [  7,  26]])

## 4. Thống kê

In [23]:
print("Min: ", np.min(a))
print("Max: ", np.max(a))
print("Mean: ", round(np.mean(a), 2))
print("Standard Deviation: ", round(np.std(a), 2))

Min:  2
Max:  100
Mean:  45.0
Standard Deviation:  33.06


In [24]:
print("Min by column: ", np.min(a, axis=0))
print("Min by row: ", np.min(a, axis=1))

Min by column:  [ 2 13  6]
Min by row:  [13  6 17  2  7]


## 5. Sort & Tìm kiếm

In [46]:
# Sort tăng dần theo dòng
np.sort(a, axis=1)

array([[13, 38, 73],
       [ 6, 10, 76],
       [17, 65, 80],
       [ 2, 72, 77],
       [ 7, 26, 51]])

In [44]:
# Tìm kiếm theo điều kiện
index = np.where(a > 8)
print("index:", index)
print("value:", a[index])

index: (array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4]), array([0, 1, 2, 0, 1, 0, 1, 2, 1, 2, 1, 2]))
value: [38 13 73 10 76 80 65 17 77 72 26 51]


## 6. Operator

In [47]:
# Cộng
c = np.array([[1, 2, 3], [1, 1, 1]])
d = np.array([[2, 2, 2]])
c + d

array([[3, 4, 5],
       [3, 3, 3]])

## 7. Utils

In [51]:
# Random low, high, size
np.random.seed(1)
np.random.randint(1, 5, size=(3,2))

array([[2, 4],
       [1, 1],
       [4, 2]])

In [57]:
# Reshape đặt lại chiều cho mảng
f = np.arange(1, 13)
f.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
# Reshape full dòng, 1 cột
f.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [60]:
# Reshape 1 dòng, full cột
f.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [61]:
# Reshape thành mảng 1 chiều
f.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])