# Mang mot chieu

## 1. Khai bao
`dtype`: Kieu du lieu cua cac phan tu trong mang numpy <br>
`size`: So phan tu <br>
`ndim`: So chieu cua mang <br>
`shape`: Kieu tuple, so chieu va so phan tu ung voi moi chieu <br>
`itemsize`: Kich thuoc phan tu trong mang

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print("a:", a, "Type of a:", type(a), "Item type:", a.dtype)

b = np.array([1, 2.3, 5])
print("b:", b, "Type of b:", type(b), "Item type:", b.dtype)

c = np.array([1, 2.3, "hi"])
print("c:", c, "Type of c:", type(c), "Item type:", c.dtype)

d = np.array([1,2,0], dtype=bool)
print("d:", d, "Type of d:", type(d), "Item type:", d.dtype)

e = np.array([1,2,0], dtype="i1")
print("e:", e, "Type of e:", type(e), "Item type:", e.dtype)

print("Size:", e.size, "Shape:", e.shape, "ndim:", e.ndim, "item size:", e.itemsize)

In [3]:
f = np.arange(1, 11)
print(f)

[ 1  2  3  4  5  6  7  8  9 10]


## 2. Truy xuat phan tu

### 2.1. Truy xuat theo index

In [ ]:
print(f[-1:-6:-1])
print(f[-1:-4:-1])
print(f[::-1]) # Invert

indexs = [0, 1, 5]
print(f[indexs])

### 2.2. Truy xuat theo dieu kien

In [ ]:
cond = f > 5
print(cond)
print(f[cond])

print(f[f % 2 == 0])
print(f[~(f % 2 == 0)])
print(f[(f > 5) & (f < 9)])

## 3. Cap nhat

In [6]:
f[:-6:-1] = 100
print(f)
f[f>=100] = f[f>=100] + 1
print(f)

[  1   2   3   4   5 100 100 100 100 100]
[  1   2   3   4   5 101 101 101 101 101]


## 4. Them

In [8]:
f1 = np.append(f, [10, 20])
print(f1)
f2 = np.insert(f, 0, [11, 22])
print(f2)
f3 = np.insert(f, [1,3], [11])
print(f3)

[  1   2   3   4   5 101 101 101 101 101  10  20]
[ 11  22   1   2   3   4   5 101 101 101 101 101]
[  1  11   2   3  11   4   5 101 101 101 101 101]


## 5. Xoa

In [9]:
f4 = np.delete(f, 1)
print(f4)

[  1   3   4   5 101 101 101 101 101]


## 6. Thong ke

In [13]:
print("Sum:", np.sum(f))
print("Min:", np.min(f))
print("Max:", np.max(f))
print("Mean:", np.mean(f))
print("Median:", np.median(f))
print("std:", np.std(f))

Sum: 520
Min: 1
Max: 101
Mean: 52.0
Median: 53.0
std: 49.01020301937138


## 7. Sort

In [15]:
print("Sort asc:", np.sort(f))
print("Sort des:", np.sort(f)[::-1])

Sort asc: [  1   2   3   4   5 101 101 101 101 101]
Sort des: [101 101 101 101 101   5   4   3   2   1]


## 8. Operator

In [39]:
print("Operator plus 1:", f + 1)
print("Phep giao:", np.intersect1d([10, 20, 40], [10, 40]))
print("Phan tu hieu:", np.setdiff1d([10, 20, 40], [10, 40]))

Operator plus 1: [  2   3   4   5   6 102 102 102 102 102]
Phep giao: [10 40]
Phan tu hieu: [20]


## 9. Utils

In [36]:
f5 = f.astype(float)
print("Ep kieu astype:", f5)

print("Array builder zeros:", np.zeros(10))
print("Array builder ones:", np.ones(10))
print("Array builder custom:", np.full(shape=(10,),fill_value=10))

print("Linspace 1:", np.linspace(2, 10, 5, endpoint=False)) # Tu 2 den 10, lay 5 phan tu, ko bao gom end
print("Linspace 2:", np.linspace(2, 10, 5, endpoint=True)) # Tu 2 den 10, lay 5 phan tu

np.random.seed(1)
print("Random int:", np.random.randint(1, 6, 2))

f6 = np.loadtxt("data.txt", delimiter=",")
print("Data file:", f6)

Array builder zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array builder ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array builder custom: [10 10 10 10 10 10 10 10 10 10]
Linspace 1: [2.  3.6 5.2 6.8 8.4]
Linspace 2: [ 2.  4.  6.  8. 10.]
Random int: [4 5]
Data file: [1.57 1.65 1.63 1.58 1.57 1.68 1.65 1.7  1.64 1.67]


# Mang nhieu chieu

## 1. Khai bao

In [53]:
a = np.array([[38, 13, 73],
       [10, 76,  6],
       [80, 65, 17],
       [ 2, 77, 72],
       [ 7, 26, 51]])
a

array([[38, 13, 73],
       [10, 76,  6],
       [80, 65, 17],
       [ 2, 77, 72],
       [ 7, 26, 51]])

## 2. Truy xuat phan tu

### 2.1. Truy xuat phan tu theo dong, cot

In [6]:
print(a[1][1])
print(a[1,1])
print(a[-1,-1])

76
76
51


### 2.2. Truy xuat nhieu phan tu
 [start:stop:step, start:stop:step]

In [18]:
print(a[1,:])
print(a[1])
print(a[:,2])
print(a[1:4,:])

[10 76  6]
[10 76  6]
[73  6 17 72 51]
[[10 76  6]
 [80 65 17]
 [ 2 77 72]]
[[38 13 73]
 [10 76  6]
 [80 65 17]
 [ 2 77 72]
 [ 7 26 51]]


In [13]:
# Lay phan tu 65, 17, 77, 72
print(a[2:4,1:])

[[65 17]
 [77 72]]


In [17]:
# Lay phan tu 10, 6, 2, 72
print(a[1::2,::2])

[[10  6]
 [ 2 72]]


In [19]:
# Lay phan tu 10, 6, 2, 72, 7, 51
print(a[[1,3,4],::2])

[[10  6]
 [ 2 72]
 [ 7 51]]


In [23]:
# Lay phan tu 80, 65, 2, 77, 7, 26
print(a[2:,:2])

[[80 65]
 [ 2 77]
 [ 7 26]]


### 2.3. Truy xuat theo dieu kien

In [26]:
print(a[a % 2 == 0])
print(a[(a % 2 == 0) & (a > 70)])
print(a[a % 3 == 0])

[38 10 76  6 80  2 72 26]
[76 80 72]
[ 6 72 51]


### 2.4. Truy xuat mang 3 chieu
tenmang[index ma tran, index dong, index cot]

In [29]:
np.random.seed(1)
b = np.random.randint(1, 101, size=(2,5,3))
b

array([[[38, 13, 73],
        [10, 76,  6],
        [80, 65, 17],
        [ 2, 77, 72],
        [ 7, 26, 51]],

       [[21, 19, 85],
        [12, 29, 30],
        [15, 51, 69],
        [88, 88, 95],
        [97, 87, 14]]])

In [35]:
print(b[0,1,1])
print(b[1,2,2])

# Truy xuat nhieu phan tu
print(b[1:]) # van giu nguyen so chieu
print(b[1]) # so chieu giam di 1

76
69
[[[21 19 85]
  [12 29 30]
  [15 51 69]
  [88 88 95]
  [97 87 14]]]
[[21 19 85]
 [12 29 30]
 [15 51 69]
 [88 88 95]
 [97 87 14]]


In [36]:
# Lay phan tu 76, 6, 65, 17, 29, 30, 51, 69
print(b[:,1:3,1:3])

[[[76  6]
  [65 17]]

 [[29 30]
  [51 69]]]


## 3. Cap nhat

In [38]:
b[0,0] = 100
print(b)

[[[100 100 100]
  [ 10  76   6]
  [ 80  65  17]
  [  2  77  72]
  [  7  26  51]]

 [[ 21  19  85]
  [ 12  29  30]
  [ 15  51  69]
  [ 88  88  95]
  [ 97  87  14]]]


## 4. Them dong, cot
**`np.insert`** or **`np.concatenate`**

In [60]:
print(a, "\n")
c = np.insert(a, 5, [1, 2, 3], axis=0)
print(c, "\n")

new_arr = np.array([[0, 0, 0, 0, 0]])
new_arr_T = new_arr.T
new_arr2 = np.array([[0], [0], [0], [0], [0]])
d = np.concatenate([a, new_arr_T], axis=1)
d = np.concatenate([d, new_arr2], axis=1)
print(d)

[[38 13 73]
 [10 76  6]
 [80 65 17]
 [ 2 77 72]
 [ 7 26 51]] 

[[38 13 73]
 [10 76  6]
 [80 65 17]
 [ 2 77 72]
 [ 7 26 51]
 [ 1  2  3]] 

[[38 13 73  0  0]
 [10 76  6  0  0]
 [80 65 17  0  0]
 [ 2 77 72  0  0]
 [ 7 26 51  0  0]]


## 5. Xoa dong, cot

In [61]:
e = np.delete(d, -1, axis=1)
print(e)

[[38 13 73  0]
 [10 76  6  0]
 [80 65 17  0]
 [ 2 77 72  0]
 [ 7 26 51  0]]


## 6. Thong ke

In [66]:
print("Min: ", np.min(a))
print("Max: ", np.max(a))
print("Mean: ", round(np.mean(a),2))
print("Standard Deviation: ", round(np.std(a),2))

Min:  2
Max:  80
Mean:  40.87
Standard Deviation:  29.62


In [71]:
print("Min by column: ", np.min(a, axis=0))
print("Min by row: ", np.min(a, axis=1))

Min by column:  [ 2 13  6]
Min by row:  [13  6 17  2  7]


## 7. Sort

## 8. Operator

## 9. Utils

In [74]:
print("Matrix builder zeros:\n", np.zeros((3,3)))
print("Matrix builder ones:\n", np.ones((3,3)))
print("Matrix builder custom:\n", np.full(shape=(3,3),fill_value=10))

Matrix builder zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matrix builder ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matrix builder custom:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
